[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[fmt]
line_length = 120
tab_width = 4

[profile.remapping]
"@openzeppelin/contracts/" = "lib/openzeppelin-contracts/contracts/"
"forge-std" = "lib/forge-std/src/"
"@aave/core-v3/"="lib/aave-v3-core/"