[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
via_ir = true

[profile.prod]
via_ir = true
optimizer = true

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
arb1 = "${ARBITRUM_RPC_URL}"

# FOUNDRY_PROFILE=prod forge build

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = 'long'
func_call_arg_multiline = true     # This makes function call arguments multi-line
multiline_func_header = 'all'      # This ensures function declarations stay multi-line
quote_style = 'double'
number_underscore = 'preserve'
single_line_statement_blocks = 'preserve'
ignore = ["src/console.sol", "src/console2.sol"]

[profile.remapping]
"@openzeppelin/contracts/" = "lib/openzeppelin-contracts/contracts/"
"forge-std" = "lib/forge-std/src/"

